# H1B Labor Condition Applications (Form ETA-9035)

In [1]:
# H1B Labor Condition Applications (Form ETA-9035)

# http://econdataus.com/h1bdata.htm

#source: US Department of Labor
#https://www.dol.gov/agencies/eta/foreign-labor/performance

#source: US Bureau of Labor Statistics 
#https://www.bls.gov/oes/tables.htm

# metadata: lca_cols
# https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Record_Layout_FY2022_Q3.pdf

# DOL Guidance on Determining OES Wage Levels
# https://www.aila.org/infonet/dol-guidance-on-determining-oes-wage-levels

# 
# https://www.dol.gov/sites/doPrevailing Wage Determination Policy Guidancelgov/files/ETA/oflc/pdfs/Policy_Nonag_Progs.pdf

# git pull https://github.com/JohnBroberg/H1B_LCA.git

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## global variables

In [2]:

#columns to be read from LCA Excel file
lca_cols = ['CASE_NUMBER','CASE_STATUS', 'RECEIVED_DATE', 'DECISION_DATE', 'ORIGINAL_CERT_DATE'
           , 'VISA_CLASS', 'SOC_CODE', 'SOC_TITLE', 'FULL_TIME_POSITION'
           , 'TOTAL_WORKER_POSITIONS', 'EMPLOYER_NAME', 'NAICS_CODE', 'WORKSITE_WORKERS'
           , 'SECONDARY_ENTITY', 'SECONDARY_ENTITY_BUSINESS_NAME', 'WORKSITE_STATE'
           , 'WAGE_RATE_OF_PAY_FROM', 'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY'
           , 'PREVAILING_WAGE', 'PW_UNIT_OF_PAY', 'PW_WAGE_LEVEL']
#           , 'PW_OES_YEAR', 'PW_OTHER_SOURCE', 'PW_OTHER_YEAR', 'PW_SURVEY_PUBLISHER', 'PW_SURVEY_NAME']

# Fiscal Year 2024

In [3]:

url = "https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Disclosure_Data_FY2024_Q3.xlsx"

df = pd.read_excel(url)

In [38]:
'''
quarter_first = 3  #2024-08/19  FY2024 has only one .xlsx file
quarter_last = 3  

data_quarter_list = []
for quarter_temp in range(quarter_first, quarter_last +1):
    url_temp = f"https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Disclosure_Data_FY2024_Q{quarter_temp}.xlsx"
    data_quarter = pd.read_excel(url_temp)
#    data_quarter = data_quarter.rename(columns={'Initial Approvals':'Initial Approval',
#                                         'Initial Denials':'Initial Denial',
#                                        'Continuing Approvals':'Continuing Approval',
#                                         'Continuing Denials':'Continuing Denial'})
    data_quarter_list.append(data_quarter)
    
df = pd.concat(data_quarter_list, ignore_index=True)
'''

'\nquarter_first = 3  #2024-08/19  FY2024 has only one .xlsx file\nquarter_last = 3  \n\ndata_quarter_list = []\nfor quarter_temp in range(quarter_first, quarter_last +1):\n    url_temp = f"https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/LCA_Disclosure_Data_FY2024_Q{quarter_temp}.xlsx"\n    data_quarter = pd.read_excel(url_temp)\n#    data_quarter = data_quarter.rename(columns={\'Initial Approvals\':\'Initial Approval\',\n#                                         \'Initial Denials\':\'Initial Denial\',\n#                                        \'Continuing Approvals\':\'Continuing Approval\',\n#                                         \'Continuing Denials\':\'Continuing Denial\'})\n    data_quarter_list.append(data_quarter)\n    \ndf = pd.concat(data_quarter_list, ignore_index=True)\n'

In [39]:


df = df[(df['VISA_CLASS']=='H-1B') & \
        (df['FULL_TIME_POSITION']=='Y')]

df

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL
0,I-200-24039-704004,Certified - Withdrawn,2024-02-08,2024-06-30,2024-02-15,H-1B,Assistant Professor,25-1042.00,"Biological Science Teachers, Postsecondary",Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
1,I-200-23201-203039,Certified - Withdrawn,2023-07-20,2024-06-30,2023-07-27,H-1B,Research Associate,27-3041.00,Editors,Y,...,No,NaN,NaN,NaN,Disclose Business and Employment,NaN,NaN,NaN,NaN,NaN
2,I-200-23174-141009,Certified - Withdrawn,2023-06-23,2024-06-30,2023-06-30,H-1B,IT Consultant,15-1221.00,Computer and Information Research Scientists,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
3,I-200-23048-783153,Certified - Withdrawn,2023-02-17,2024-06-30,2023-02-24,H-1B,"IT Manager, Oracle",15-1299.09,Information Technology Project Managers,Y,...,No,NaN,NaN,NaN,Disclose Business,Raffo,Maria,A,"Fragomen, Del Rey, Bernsen & Loewy, LLP",mraffo@fragomen.com
4,I-200-23034-750291,Certified - Withdrawn,2023-02-03,2024-06-30,2023-02-10,H-1B,Director of Business Operations and Planning,15-2051.01,Business Intelligence Analysts,Y,...,No,NaN,NaN,NaN,Disclose Business,Webster,Sumiko,NaN,"Fragomen, Del Rey, Bernsen & Loewy, LLP",sumiko.webster@fragomen.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442370,I-200-23271-388903,Withdrawn,2023-09-28,2023-10-02,NaT,H-1B,"Senior Scientist, Analytical Development, Mana...",19-2031.00,Chemists,Y,...,No,NaN,NaN,NaN,Disclose Employment,NaN,NaN,NaN,NaN,NaN
442371,I-200-23269-381471,Withdrawn,2023-09-26,2023-10-02,NaT,H-1B,Strategic Analyst,15-2051.01,Business Intelligence Analysts,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
442372,I-200-23269-381475,Withdrawn,2023-09-26,2023-10-02,NaT,H-1B,System Analyst - Ignition SCADA Software and MQTT,15-1211.00,Computer Systems Analysts,Y,...,No,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
442373,I-200-23269-381803,Withdrawn,2023-09-26,2023-10-02,NaT,H-1B,Attorney,23-1011.00,Lawyers,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
442374,I-200-23269-382958,Withdrawn,2023-09-26,2023-10-02,NaT,H-1B,Postdoctoral Research Associate,19-2012.00,Physicists,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN

In [40]:
# check fig. 423986 rows × 96 columns

In [41]:
min(df['DECISION_DATE'])

Timestamp('2023-10-02 00:00:00')

In [42]:
max(df['DECISION_DATE'])

Timestamp('2024-06-30 00:00:00')

In [43]:
# check fig. #Timestamp('2024-06-30 00:00:00')

In [44]:
df24 = df

In [45]:
# number of duplicate rows
len(df24)-len(df24.drop_duplicates())

0

In [46]:
# number of duplicate Case Numbers
len(df24['CASE_NUMBER'])-len(df24['CASE_NUMBER'].drop_duplicates())

0

In [47]:
# remove duplcate cases, keeping row with latest Decision Date

df24 = df24.sort_values(['CASE_NUMBER', 'DECISION_DATE'], ascending = False) \
    .drop_duplicates(subset = 'CASE_NUMBER', keep = 'first', ignore_index = True)

In [48]:
# number of duplicate Case Numbers
len(df24['CASE_NUMBER'])-len(df24['CASE_NUMBER'].drop_duplicates())

0

In [49]:
#dup = df24[df24.duplicated(['CASE_NUMBER'], keep = False)]\
#     .sort_values(['CASE_NUMBER', 'DECISION_DATE'], ascending = False)

#dup

In [50]:
df24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423986 entries, 0 to 423985
Data columns (total 96 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CASE_NUMBER                     423986 non-null  object
 1   CASE_STATUS                     423986 non-null  object
 2   RECEIVED_DATE                   423986 non-null  datetime64[ns]
 3   DECISION_DATE                   423986 non-null  datetime64[ns]
 4   ORIGINAL_CERT_DATE              23130 non-null   datetime64[ns]
 5   VISA_CLASS                      423986 non-null  object
 6   JOB_TITLE                       423986 non-null  object
 7   SOC_CODE                        423986 non-null  object
 8   SOC_TITLE                       423986 non-null  object
 9   FULL_TIME_POSITION              423986 non-null  object
 10  BEGIN_DATE                      423986 non-null  datetime64[ns]
 11  END_DATE                        423986 non-null  datetime64[ns]
 12  TOTAL_WORKER_POSITIONS          423986 non-null  int64
 13  NEW_EMPLOYMENT                  423986 non-null  int64
 14  CONTINUED_EMPLOYMENT            423986 non-null  int64
 15  CHANGE_PREVIOUS_EMPLOYMENT      423986 non-null  int64
 16  NEW_CONCURRENT_EMPLOYMENT       423986 non-null  int64
 17  CHANGE_EMPLOYER                 423986 non-null  int64
 18  AMENDED_PETITION                423986 non-null  int64
 19  EMPLOYER_NAME                   423986 non-null  object
 20  TRADE_NAME_DBA                  37220 non-null   object
 21  EMPLOYER_ADDRESS1               423986 non-null  object
 22  EMPLOYER_ADDRESS2               193486 non-null  object
 23  EMPLOYER_CITY                   423986 non-null  object
 24  EMPLOYER_STATE                  423914 non-null  object
 25  EMPLOYER_POSTAL_CODE            423986 non-null  object
 26  EMPLOYER_COUNTRY                423986 non-null  object
 27  EMPLOYER_PROVINCE               23149 non-null   object
 28  EMPLOYER_PHONE                  423986 non-null  int64
 29  EMPLOYER_PHONE_EXT              24254 non-null   float64
 30  NAICS_CODE                      423986 non-null  int64
 31  EMPLOYER_POC_LAST_NAME          423986 non-null  object
 32  EMPLOYER_POC_FIRST_NAME         423983 non-null  object
 33  EMPLOYER_POC_MIDDLE_NAME        72853 non-null   object
 34  EMPLOYER_POC_JOB_TITLE          423986 non-null  object
 35  EMPLOYER_POC_ADDRESS1           423986 non-null  object
 36  EMPLOYER_POC_ADDRESS2           199625 non-null  object
 37  EMPLOYER_POC_CITY               423986 non-null  object
 38  EMPLOYER_POC_STATE              423683 non-null  object
 39  EMPLOYER_POC_POSTAL_CODE        423986 non-null  object
 40  EMPLOYER_POC_COUNTRY            423986 non-null  object
 41  EMPLOYER_POC_PROVINCE           3776 non-null    object
 42  EMPLOYER_POC_PHONE              423986 non-null  int64
 43  EMPLOYER_POC_PHONE_EXT          21684 non-null   float64
 44  EMPLOYER_POC_EMAIL              412515 non-null  object
 45  AGENT_REPRESENTING_EMPLOYER     423986 non-null  object
 46  AGENT_ATTORNEY_LAST_NAME        309934 non-null  object
 47  AGENT_ATTORNEY_FIRST_NAME       309933 non-null  object
 48  AGENT_ATTORNEY_MIDDLE_NAME      155872 non-null  object
 49  AGENT_ATTORNEY_ADDRESS1         309934 non-null  object
 50  AGENT_ATTORNEY_ADDRESS2         247623 non-null  object
 51  AGENT_ATTORNEY_CITY             309934 non-null  object
 52  AGENT_ATTORNEY_STATE            295136 non-null  object
 53  AGENT_ATTORNEY_POSTAL_CODE      309934 non-null  object
 54  AGENT_ATTORNEY_COUNTRY          309934 non-null  object
 55  AGENT_ATTORNEY_PROVINCE         35418 non-null   object
 56  AGENT_ATTORNEY_PHONE            309934 non-null  float64
 57  AGENT_ATTORNEY_PHONE_EXT        17330 non-null   float64
 58  AGENT_ATTORNEY_EMAIL_ADDRESS    309929 non-null  object
 59  LAWFIRM_NAME_BUSINESS_NAME      309934 non-null  object
 60  STATE_OF_HIGHEST_COURT          309126 non-null  object
 61  NAME_OF_HIGHEST_STATE_COURT     308858 non-null  object
 62  WORKSITE_WORKERS                423986 non-null  int64
 63  SECONDARY_ENTITY                423986 non-null  object
 64  SECONDARY_ENTITY_BUSINESS_NAME  91112 non-null   object
 65  WORKSITE_ADDRESS1               423986 non-null  object
 66  WORKSITE_ADDRESS2               129675 non-null  object
 67  WORKSITE_CITY                   423984 non-null  object
 68  WORKSITE_COUNTY                 423984 non-null  object
 69  WORKSITE_STATE                  423986 non-null  object
 70  WORKSITE_POSTAL_CODE            423986 non-null  object
 71  WAGE_RATE_OF_PAY_FROM           423986 non-null  float64
 72  WAGE_RATE_OF_PAY_TO             137825 non-null  float64
 73  WAGE_UNIT_OF_PAY                423986 non-null  object
 74  PREVAILING_WAGE                 423986 non-null  float64
 75  PW_UNIT_OF_PAY                  423986 non-null  object
 76  PW_TRACKING_NUMBER              719 non-null     object
 77  PW_WAGE_LEVEL                   391032 non-null  object
 78  PW_OES_YEAR                     393218 non-null  object
 79  PW_OTHER_SOURCE                 30049 non-null   object
 80  PW_OTHER_YEAR                   30049 non-null   float64
 81  PW_SURVEY_PUBLISHER             25254 non-null   object
 82  PW_SURVEY_NAME                  25253 non-null   object
 83  TOTAL_WORKSITE_LOCATIONS        423986 non-null  int64
 84  AGREE_TO_LC_STATEMENT           423986 non-null  object
 85  H_1B_DEPENDENT                  423986 non-null  object
 86  WILLFUL_VIOLATOR                423986 non-null  object
 87  SUPPORT_H1B                     112308 non-null  object
 88  STATUTORY_BASIS                 111658 non-null  object
 89  APPENDIX_A_ATTACHED             206 non-null     object
 90  PUBLIC_DISCLOSURE               423936 non-null  object
 91  PREPARER_LAST_NAME              215128 non-null  object
 92  PREPARER_FIRST_NAME             215130 non-null  object
 93  PREPARER_MIDDLE_INITIAL         60347 non-null   object
 94  PREPARER_BUSINESS_NAME          219715 non-null  object
 95  PREPARER_EMAIL                  218388 non-null  object
dtypes: datetime64[ns](5), float64(8), int64(12), object(71)
memory usage: 310.5+ MB

In [51]:
# Add WORKSITE_EMPLOYER column

df24['WORKSITE_EMPLOYER'] = df24['EMPLOYER_NAME']
df24.loc[df24['SECONDARY_ENTITY'] == 'Yes', 'WORKSITE_EMPLOYER'] = df24['SECONDARY_ENTITY_BUSINESS_NAME']

df24[['EMPLOYER_NAME','SECONDARY_ENTITY_BUSINESS_NAME','WORKSITE_EMPLOYER']]

,EMPLOYER_NAME,SECONDARY_ENTITY_BUSINESS_NAME,WORKSITE_EMPLOYER
0,Sabre GLBL Inc.,NaN,Sabre GLBL Inc.
1,Sabre GLBL Inc.,NaN,Sabre GLBL Inc.
2,Sabre GLBL Inc.,NaN,Sabre GLBL Inc.
3,"University of California, Berkeley",NaN,"University of California, Berkeley"
4,Relanto Inc,Cisco Systems Inc,Cisco Systems Inc
...,...,...,...
423981,Georgia Institute of Technology,NaN,Georgia Institute of Technology
423982,Stiaos Technologies,NaN,Stiaos Technologies
423983,Apex IT Services LLC,US BANK,US BANK
423984,Stiaos Technologies,NaN,Stiaos Technologies
423985,NEUMERIC TECHNOLOGIES CORPORATION,JOHNSON CONTROLS INTERNATIONAL PLC,JOHNSON CONTROLS INTERNATIONAL PLC

In [52]:
# df24['WORKSITE_EMPLOYER'] = df24['WORKSITE_EMPLOYER'].str.upper()
# df24['WORKSITE_EMPLOYER']

In [53]:
# Facebook changes company name to Meta
# https://www.cnbc.com/2021/10/28/facebook-changes-company-name-to-meta.html

#Excel function =CONCAT(", ", "'",A2, "':'",$A$1,"'")



dict_emp = {'Meta Platforms, Inc. ':'Meta Platforms, Inc.'
            , '="Meta Platforms, Inc. "Facebook""':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc':'Meta Platforms, Inc.'
            , 'META Platforms INC':'Meta Platforms, Inc.'
            , 'META PLATFORMS, INC. (FACEBOOK, INC.)':'Meta Platforms, Inc.'
            , 'Meta Platforms':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc. (â€œFacebookâ€)':'Meta Platforms, Inc.'
            , 'Meta Inc':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc.':'Meta Platforms, Inc.'
            , 'Meta Plaforms, Inc.':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc;Â ':'Meta Platforms, Inc.'
            , '="Meta Platforms Inc. ("Facebook")"':'Meta Platforms, Inc.'
            , 'Meta/Facebook':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc., DBA â€œMetaâ€':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc. (META)':'Meta Platforms, Inc.'
            , 'Facebook/Meta':'Meta Platforms, Inc.'
            , 'Meta,':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc. f/k/a Facebook, Inc.':'Meta Platforms, Inc.'
            , 'New Meta Entertainment, Inc.':'Meta Platforms, Inc.'
            , 'Meta (Facebook ,Inc)':'Meta Platforms, Inc.'
            , 'Meta (Facebook)':'Meta Platforms, Inc.'
            , 'HCL-Meta':'Meta Platforms, Inc.'
            , 'Meta (Facebook) (Remote Work Location)':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc. d/b/a Meta':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc.,':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc., â€œFacebookâ€':'Meta Platforms, Inc.'
            , '="Meta Platforms, Inc. ("Facebook")"':'Meta Platforms, Inc.'
            , 'META SOFT INC':'Meta Platforms, Inc.'
            , 'Meta Inc.':'Meta Platforms, Inc.'
            , 'Meta- Managed Service':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc (Facebook Inc)':'Meta Platforms, Inc.'
            , '(Giphy) Meta':'Meta Platforms, Inc.'
            , 'META Platforms Inc Office':'Meta Platforms, Inc.'
            , 'META PLATFORMS, INC. ':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc. (â€œFacebookâ€)':'Meta Platforms, Inc.'
            , 'Meta Payments, Inc.':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc;Â ':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc., â€œFacebookâ€':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc. (Facebook, Inc.)':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc., DBA â€œMetaâ€':'Meta Platforms, Inc.'
            , 'Meta INC':'Meta Platforms, Inc.'
            , 'META PLATFORMS, INC':'Meta Platforms, Inc.'

            , 'Facebook Inc':'Meta Platforms, Inc.'
            , 'Facebook':'Meta Platforms, Inc.'
            , 'Meta Platforms Inc. (â€œFacebookâ€)':'Meta Platforms, Inc.'
            , 'HCL AMERICA / FACEBOOK':'Meta Platforms, Inc.'
            , 'FACEBOOK , INC':'Meta Platforms, Inc.'
            , 'Facebook Technologies, LLC':'Meta Platforms, Inc.'
            , 'Facebook, Inc':'Meta Platforms, Inc.'
            , 'Quest Global Services / Facebook':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc., â€œFacebookâ€':'Meta Platforms, Inc.'
            , 'Meta Platforms, Inc. (Facebook, Inc.)':'Meta Platforms, Inc.'
            , 'Facebook, Inc.':'Meta Platforms, Inc.'

            
            , 'AMAZON WEB SERVICES, INC.':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTER U.S., INC.':'AMAZON.COM SERVICES LLC'
            , 'Remote Work From Home for Amazon':'AMAZON.COM SERVICES LLC'
            , 'Remote work From Home for Amazon':'AMAZON.COM SERVICES LLC'
            , 'Amazon Data Services, Inc.':'AMAZON.COM SERVICES LLC'
            , 'AMAZON':'AMAZON.COM SERVICES LLC'
            , 'AMAZON ADVERTISING LLC':'AMAZON.COM SERVICES LLC'
            , 'AMAZON.COM, INC.':'AMAZON.COM SERVICES LLC'
            , 'Work From home for Amazon':'AMAZON.COM SERVICES LLC'
            , 'Amazon com Inc':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com Services Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com Inc':'AMAZON.COM SERVICES LLC'
            , 'AMAZON (REMOTE WORK)':'AMAZON.COM SERVICES LLC'
            , 'Amazon Web Services Inc. ':'AMAZON.COM SERVICES LLC'
            , 'AMAZON CAPITAL SERVICES, INC.':'AMAZON.COM SERVICES LLC'
            , 'Persistent/Amazon':'AMAZON.COM SERVICES LLC'
            , 'AMAZON (TELECOMMUTING)':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTER U.S. INC.':'AMAZON.COM SERVICES LLC'
            , 'Remote Worksite (Amazon)':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com':'AMAZON.COM SERVICES LLC'
            , 'Amazon, Inc. ':'AMAZON.COM SERVICES LLC'
            , 'Amazon Web Services, Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Development Center U.S., Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Data Services, Inc':'AMAZON.COM SERVICES LLC'
            , 'Amazon Advertising LLC':'AMAZON.COM SERVICES LLC'
            , 'Amazon Web Services Inc':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DATA SERVICES, INC.':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com.ca, Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Media Venture LLC':'AMAZON.COM SERVICES LLC'
            , 'Amazon Payments, Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DATA SERVICES, INC. ':'AMAZON.COM SERVICES LLC'
            , 'Amazon Capital Services, Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Studios, LLC':'AMAZON.COM SERVICES LLC'
            , 'Remote work from Home for Amazon':'AMAZON.COM SERVICES LLC'
            , 'Remote Work from Home for Amazon':'AMAZON.COM SERVICES LLC'
            , 'Amazon Development Center U.S. Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Mechanical Turk, Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Robotics LLC':'AMAZON.COM SERVICES LLC'
            , 'Amazon Web Services Inc.':'AMAZON.COM SERVICES LLC'
            , 'Amazon Retail LLC ':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTER U.S., INC. ':'AMAZON.COM SERVICES LLC'
            , 'Amazon Media Venture LLC ':'AMAZON.COM SERVICES LLC'
            , 'AMAZON CAPITAL SERVICES, INC.':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com, Inc.':'AMAZON.COM SERVICES LLC'
            , 'AMAZON DEVELOPMENT CENTR U.S., INC.':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com.ca, Inc. (US)':'AMAZON.COM SERVICES LLC'
            , 'Work from home for amazon':'AMAZON.COM SERVICES LLC'
            , 'Amazon Web Services, Inc. ':'AMAZON.COM SERVICES LLC'
            , 'Amazon Fresh LLC':'AMAZON.COM SERVICES LLC'
            , 'Amazon.com Services LLC':'AMAZON.COM SERVICES LLC'

            , 'Qualcomm':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Inc.':'Qualcomm Technologies, Inc.'
            , 'Qualcomm, Inc. ':'Qualcomm Technologies, Inc.'
            , 'Qualcomm ':'Qualcomm Technologies, Inc.'
            , 'Arriver/Qualcomm':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Technologies Inc.':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Atheros, Inc. ':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Innovation Center, Inc. ':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Incorporated':'Qualcomm Technologies, Inc.'
            , 'Qualcomm Innovation Center, Inc.':'Qualcomm Technologies, Inc.'

            , 'CISCO Systems Inc':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS INC.':'Cisco Systems, Inc.'
            , 'Cisco':'Cisco Systems, Inc.'
            , 'Cisco Systems, Inc':'Cisco Systems, Inc.'
            , 'CISCO Systems':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc ':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS INC.,':'Cisco Systems, Inc.'
            , 'Cisco System Inc':'Cisco Systems, Inc.'
            , 'Cisco Systems, Inc. ':'Cisco Systems, Inc.'
            , 'Cisco System Inc.':'Cisco Systems, Inc.'
            , 'Cisco Systems, Inc  ':'Cisco Systems, Inc.'
            , 'CISCO ':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc. ':'Cisco Systems, Inc.'
            , 'TCS/Cisco':'Cisco Systems, Inc.'
            , 'Cisco Systems (Remote Working)':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc, USA':'Cisco Systems, Inc.'
            , 'REMOTE LOCATION - (CISCO)':'Cisco Systems, Inc.'
            , 'Cisco Systems, Inc. (Working Remotely)':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS INC (REMOTE)':'Cisco Systems, Inc.'
            , 'Cisco Systems, Inc.(Remote Work Location)':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc / Remote':'Cisco Systems, Inc.'
            , 'Remote Location (CISCO)':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc / Remote ':'Cisco Systems, Inc.'
            , '(Remote) Cisco Systems, Inc':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS INC':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc.':'Cisco Systems, Inc.'
            , 'CISCO':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS, INC':'Cisco Systems, Inc.'
            , 'Cisco Systems':'Cisco Systems, Inc.'
            , 'Cisco Systems Inc.,':'Cisco Systems, Inc.'
            , 'CISCO System Inc.':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS INC':'Cisco Systems, Inc.'
            , 'CISCO SYSTEMS':'Cisco Systems, Inc.'
            , 'CISCO Systems Inc.':'Cisco Systems, Inc.'
            , 'Cisco systems':'Cisco Systems, Inc.'

            , 'Ernst & Young':'Ernst & Young U.S. LLP'
            , 'Ernst &  Young':'Ernst & Young U.S. LLP'
            , 'TCS / ERNST & YOUNG':'Ernst & Young U.S. LLP'
            , 'Ernst &Young':'Ernst & Young U.S. LLP'
            , 'Ernst And Young - American Family Insurance':'Ernst & Young U.S. LLP'
            , 'Ernst and Young LLC':'Ernst & Young U.S. LLP'
            , 'Ernst & Young / Fortive Corporation':'Ernst & Young U.S. LLP'
            , '(Remote) Ernst & Young':'Ernst & Young U.S. LLP'
            , 'Ernst & Young L.L.P. ':'Ernst & Young U.S. LLP'
            , 'Ernst & Young LLP (EY GUAM)':'Ernst & Young U.S. LLP'
            , 'ERNST & YOUNG':'Ernst & Young U.S. LLP'

            , 'GOOGLE':'Google LLC'
            , 'Google Inc':'Google LLC'
            , 'Google Inc.':'Google LLC'
            , 'Google Public Sector LLC ':'Google LLC'
            , 'Google ':'Google LLC'
            , 'Google, Inc':'Google LLC'
            , 'Google, LLC':'Google LLC'
            , 'Google LLC ':'Google LLC'
            , 'Google (Remote)':'Google LLC'
            , 'Google, Inc.':'Google LLC'
            , 'GOOGLE LLC.':'Google LLC'
            , ' Google Inc':'Google LLC'
            , 'FOR GOOGLE':'Google LLC'
            , 'Remote work from Residence for Google':'Google LLC'
            , 'Google, Inc. (Remote Home Office)':'Google LLC'
            , 'Google (Remote Working)':'Google LLC'
            , 'Google, Inc. (Working Remotely)':'Google LLC'
            , 'HCL America, Inc./Google LLC':'Google LLC'
            , 'Google Fiber':'Google LLC'
            , 'Google Public Sector LLC':'Google LLC'
            , 'HCL/ Google':'Google LLC'
            , 'Google ,':'Google LLC'
            , 'Working Remotely for Google':'Google LLC'
            , 'Google(Remote)':'Google LLC'
            , 'Google Austin':'Google LLC'
            , 'Google':'Google LLC'
            , 'GOOGLE INC':'Google LLC'
            , 'GOOGLE Inc.':'Google LLC'
            , 'Google LLC.':'Google LLC'
            
            , 'Oracle America, Inc':'Oracle America, Inc.'
            , 'ORACLE FINANCIAL SERVICES SOFTWARE, INC.':'Oracle America, Inc.'
            , 'Oracle America, Inc. ':'Oracle America, Inc.'
            , 'Telecommuter to Oracle Corporation ':'Oracle America, Inc.'
            , 'Telecommuter to Oracle Corporation':'Oracle America, Inc.'
            , 'Oracle America Inc':'Oracle America, Inc.'
            , 'ORACLE':'Oracle America, Inc.'
            
            , 'McKinsey & Company, Inc':'McKinsey & Company, Inc. United States'
            , 'MCKINSEY & COMPANY':'McKinsey & Company, Inc. United States'
            , 'McKinsey and Company, Inc.':'McKinsey & Company, Inc. United States'

            , 'Apple, Inc.':'Apple Inc.'
            , 'Apple Inc':'Apple Inc.'
            , 'APPLE':'Apple Inc.'
            , 'Apple, Inc. ':'Apple Inc.'
            , 'APPLE PROCESSING  LLC':'Apple Inc.'
            , 'Apple, Inc':'Apple Inc.'
            , 'TCS/APPLE':'Apple Inc.'
            , 'Apple ':'Apple Inc.'
            , 'APPLE PROCESSING LLC':'Apple Inc.'
            , 'Apple,  Inc.':'Apple Inc.'
            , 'Apple American Group LLC':'Apple Inc.'
            , 'Apple Computer Inc':'Apple Inc.'
            , 'APPLE INC (TELECOMMUTING)':'Apple Inc.'
            , 'APPLE INC ':'Apple Inc.'
            , 'Apple Financing LLC':'Apple Inc.'
            , 'Apple Corporation':'Apple Inc.'
            , 'Infosys / Apple ':'Apple Inc.'
            , 'Remote Worksite (Apple Inc.) ':'Apple Inc.'
            , 'Infosys/Apple Inc.':'Apple Inc.'
            , 'TCS / Apple Inc':'Apple Inc.'
            , 'Apple .':'Apple Inc.'
            , '(Remote) Apple Computer Inc':'Apple Inc.'
            , 'Apple, Inc. (Vendor\'s location)':'Apple Inc.'
            , 'Â Apple, Inc':'Apple Inc.'
            , 'Apple/TCS':'Apple Inc.'
            , 'APPLE - AGILEONE':'Apple Inc.'
            , 'Apple Inc / Remote':'Apple Inc.'
            , 'Apple, IncÂ ':'Apple Inc.'
            , 'Apple Inc,':'Apple Inc.'
            , 'Cognizant/ Apple':'Apple Inc.'
            , 'TCS/ APPLE':'Apple Inc.'
            , 'InfoSys/Apple':'Apple Inc.'
            , ' Apple, Inc. ':'Apple Inc.'
            , 'Remote Worksite (Apple Inc.)':'Apple Inc.'
            , 'TCS / Apple':'Apple Inc.'
            , 'Apple Inc.,':'Apple Inc.'
            , 'APPLE (WORK FROM HOME)':'Apple Inc.'
            , 'Â Apple, Inc(Remote)':'Apple Inc.'
            , ' Apple':'Apple Inc.'
            , 'Apple Inc. ':'Apple Inc.'

            , 'Microsoft':'Microsoft Corporation'
            , 'Remote Work from Home for Microsoft':'Microsoft Corporation'
            , 'Microsoft Corporation ':'Microsoft Corporation'
            , 'Microsoft Inc':'Microsoft Corporation'
            , 'Microsoft Corporation(Remote Work Location)':'Microsoft Corporation'
            , 'MICROSOFT - REMOTE':'Microsoft Corporation'
            , 'Microsoft Technology Center':'Microsoft Corporation'
            , 'Microsoft (Beneficiary\'s Residence - Remote Work Location) ':'Microsoft Corporation'
            , 'TCS/Microsoft (Remote work)':'Microsoft Corporation'
            , 'Microsoft (Remote)':'Microsoft Corporation'
            , 'MICROSOFT ( REMOTE WORK)':'Microsoft Corporation'
            , 'Microsoft Corportation':'Microsoft Corporation'
            , 'Microsoft ':'Microsoft Corporation'
            , 'MicroSoft/ Remote':'Microsoft Corporation'
            , ' Microsoft Corporation':'Microsoft Corporation'
            , 'TCS/Microsoft - Remote':'Microsoft Corporation'
            , 'Microsoft Corporation (Working Remotely)':'Microsoft Corporation'
            , 'Microsoft ( Remote )':'Microsoft Corporation'
            , 'MICROSOFT':'Microsoft Corporation'
            , 'Remote Work From Home for Microsoft':'Microsoft Corporation'

            , 'Intel Corporation':'Intel Corporation '
            , 'Intel Americas, Inc. ':'Intel Corporation '
            , 'Intel':'Intel Corporation '
            , 'INTEL ':'Intel Corporation '
            , 'Intel Americas':'Intel Corporation '

            , 'Cognizant TriZetto Software Group, Inc.':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Trizetto Corporation - A Cognizant Company':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'COGNIZANT':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions_IQN/ TD Bank':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions US Corporation':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Mobility, Inc.':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'TMG HEALTH - A COGNIZANT COMPANY':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'TIAA CREF / COGNIZANT (REMOTE)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Anthem Inc. and Cognizant Technology Solutions US Corp.':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant ':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions/CVS Health':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions (CTS) ':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant/ Apple':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions [Project for PepsiCo (Remotely working from home)]':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions(Project for Ford Motor Company)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant / Liberty Mutual Insurance':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solution [Project for Centene Corporation] [Working Remotely from Home Office]':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'TD Bank/ Cognizant':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'COGNIZANT WORLDWIDE LIMITED':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant / American Express':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant/BSC':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technologies Serives':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Services (REMOTE / WFH)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'AIG / COGNIZANT':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions project for CVS Pharmacy,Inc. (Remotely working from home office)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions project for Columbia Sportswear Company(Remotely working from home Office)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'
            , 'Cognizant Technology Solutions project for CVS Pharmacy, Inc. (Remotely working from home office)':'COGNIZANT TECHNOLOGY SOLUTIONS US CORP'

            , 'Infosys':'INFOSYS LIMITED'
            , 'Srivin Infosystems, Inc.':'INFOSYS LIMITED'
            , 'INFOSYS BPM LIMITED':'INFOSYS LIMITED'
            , 'INFOSYS MCCAMISH SYSTEMS, LLC ':'INFOSYS LIMITED'
            , 'CHARTER COMMUNICATIONS / INFOSYS':'INFOSYS LIMITED'
            , 'Vectra Infosys, Inc.':'INFOSYS LIMITED'
            , 'INFOSYS MCCAMISH SYSTEMS, LLC':'INFOSYS LIMITED'
            , 'BRENNTAG / INFOSYS (TELECOMMUTING)':'INFOSYS LIMITED'
            , 'Infosys/Molina Healthcare':'INFOSYS LIMITED'
            , 'Infosys [Project for Premium Brands] (Remotely working from home)':'INFOSYS LIMITED'
            , 'STERLING INFOSYSTEMS, INC.':'INFOSYS LIMITED'
            , 'PROSPECT INFOSYSTEM, INC.':'INFOSYS LIMITED'
            , 'Infosys/UBS':'INFOSYS LIMITED'
            , 'Remotely working for Infosys':'INFOSYS LIMITED'
            , 'Infosys Ltd':'INFOSYS LIMITED'
            , 'NOUS INFOSYSTEMS PVT. LTD.':'INFOSYS LIMITED'
            , 'INFOSYS McCAMISH SYSTEMS LLC':'INFOSYS LIMITED'
            , 'Rave Infosys, Inc.':'INFOSYS LIMITED'
            , 'Infosys / BP North America Inc':'INFOSYS LIMITED'
            , 'Infosys/T-Mobile':'INFOSYS LIMITED'
            , 'INFOSYS ( REMOTE )':'INFOSYS LIMITED'
            , 'Infosys/Walmart':'INFOSYS LIMITED'
            , 'BP/ Infosys Pontoon':'INFOSYS LIMITED'
            , 'Peloton Interactive/ Infosys':'INFOSYS LIMITED'
            , 'Direct TV / Infosys (Implementation Partner)':'INFOSYS LIMITED'
            , 'Prospect Infosystem, Inc. ':'INFOSYS LIMITED'
            , 'GAP, INC THROUGH INFOSYS':'INFOSYS LIMITED'
            , 'Remote work from Residence for Infosys/Hallmark':'INFOSYS LIMITED'
            , 'INFOSYS/FISERV':'INFOSYS LIMITED'
            , 'INFOSYS (TELECOMMUTING)':'INFOSYS LIMITED'
            , 'CGINFOSYS Inc':'INFOSYS LIMITED'
            , 'Infosys Public Systems (Telecommuting From)':'INFOSYS LIMITED'
            , 'Infosys/ United Airlines':'INFOSYS LIMITED'
            , 'Infosys Project for Atlice USA':'INFOSYS LIMITED'
            
            , 'GOLDMAN  SACHS (REMOTE)':'Goldman Sachs'
            , 'Goldman Property Management, LLC':'Goldman Sachs'
            , 'Goldman Sachs':'Goldman Sachs'
            , 'Goldman Sachs ':'Goldman Sachs'
            , 'Goldman Sachs & Co':'Goldman Sachs'
            , 'GOLDMAN SACHS & CO LLC':'Goldman Sachs'
            , 'GOLDMAN SACHS & CO.':'Goldman Sachs'
            , 'GOLDMAN SACHS & CO. LLC':'Goldman Sachs'
            , 'GOLDMAN SACHS BANK USA':'Goldman Sachs'
            , 'Goldman Sachs Group Inc.':'Goldman Sachs'
            , 'Goldman Sachs Group, Inc.':'Goldman Sachs'
            , 'Goldman Sachs HQ ':'Goldman Sachs'
            , 'Goldman Sachs Inc.':'Goldman Sachs'
            , 'GOLDMAN SACHS SERVICES LLC':'Goldman Sachs'
            , 'GoldmanSachs':'Goldman Sachs'
            , 'GoldmanSachs (Remote)':'Goldman Sachs'
            , 'Infosys / Goldman Sachs':'Goldman Sachs'
            , 'The Ayco Company, L.P., a Goldman Sachs Company':'Goldman Sachs'
            , 'The Goldman Sachs Group Inc':'Goldman Sachs'
            , 'The Goldman Sachs Group Inc ':'Goldman Sachs'
            , 'The Goldman Sachs Group, Inc':'Goldman Sachs'
            , 'The Goldman Sachs Group, Inc.':'Goldman Sachs'

           }

# df24.WORKSITE_EMPLOYER = df24.WORKSITE_EMPLOYER.replace(dict_emp)  
df24['WORKSITE_EMPLOYER'] = df24['WORKSITE_EMPLOYER'].replace(dict_emp)

In [54]:

# Fill in missing values with an empty string
df24['WORKSITE_EMPLOYER'] = df24['WORKSITE_EMPLOYER'].fillna('')

# Replace values in the 'WORKSITE_EMPLOYER' column based on condition contains('FACEBOOK')
# mask = df24['WORKSITE_EMPLOYER'].str.contains('FACEBOOK')
# df24.loc[mask, 'WORKSITE_EMPLOYER'] = 'META PLATFORMS INC'

In [55]:
df24

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL,WORKSITE_EMPLOYER
0,I-200-24181-162896,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Quality Engineer,15-1253.00,Software Quality Assurance Analysts and Testers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
1,I-200-24181-162893,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Lead Software Engineer,15-1252.00,Software Developers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
2,I-200-24181-162884,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Engineer,15-1299.08,Computer Systems Engineers/Architects,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
3,I-200-24181-162700,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Assistant Professor,25-1032.00,"Engineering Teachers, Postsecondary",Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"University of California, Berkeley"
4,I-200-24181-162574,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Software Developer,15-1251.00,Computer Programmers,Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"Cisco Systems, Inc."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423981,I-200-19297-106681,Certified - Withdrawn,2019-10-24,2023-11-01,2019-10-31,H-1B,Research Scientist I,17-2031.00,Biomedical Engineers,Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,Georgia Institute of Technology
423982,I-200-19296-103874,Certified - Withdrawn,2019-10-23,2024-03-04,2019-10-30,H-1B,Java Backend Microservices Designer / Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423983,I-200-19295-102430,Certified - Withdrawn,2019-10-22,2024-02-08,2019-10-29,H-1B,Senior Tibco Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,US BANK
423984,I-200-19288-087953,Certified - Withdrawn,2019-10-15,2024-03-04,2019-10-22,H-1B,BI Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423985,I-200-19287-084931,Certified - Withdrawn,2019-10-14,2024-04-01,2019-10-21,H-1B,SENIOR SOFTWARE ENGINEER,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,JOHNSON CONTROLS INTERNATIONAL PLC

In [56]:
rslt_df = df24[df24['WAGE_UNIT_OF_PAY'] == 'Year'] 
rslt_df

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL,WORKSITE_EMPLOYER
0,I-200-24181-162896,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Quality Engineer,15-1253.00,Software Quality Assurance Analysts and Testers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
1,I-200-24181-162893,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Lead Software Engineer,15-1252.00,Software Developers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
2,I-200-24181-162884,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Engineer,15-1299.08,Computer Systems Engineers/Architects,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
3,I-200-24181-162700,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Assistant Professor,25-1032.00,"Engineering Teachers, Postsecondary",Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"University of California, Berkeley"
4,I-200-24181-162574,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Software Developer,15-1251.00,Computer Programmers,Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"Cisco Systems, Inc."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423981,I-200-19297-106681,Certified - Withdrawn,2019-10-24,2023-11-01,2019-10-31,H-1B,Research Scientist I,17-2031.00,Biomedical Engineers,Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,Georgia Institute of Technology
423982,I-200-19296-103874,Certified - Withdrawn,2019-10-23,2024-03-04,2019-10-30,H-1B,Java Backend Microservices Designer / Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423983,I-200-19295-102430,Certified - Withdrawn,2019-10-22,2024-02-08,2019-10-29,H-1B,Senior Tibco Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,US BANK
423984,I-200-19288-087953,Certified - Withdrawn,2019-10-15,2024-03-04,2019-10-22,H-1B,BI Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423985,I-200-19287-084931,Certified - Withdrawn,2019-10-14,2024-04-01,2019-10-21,H-1B,SENIOR SOFTWARE ENGINEER,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,JOHNSON CONTROLS INTERNATIONAL PLC

In [57]:
# len(rslt_df[rslt_df['WAGE_DIFF'] < 0])

In [58]:
# rslt_df = rslt_df['WAGE_DIFF']
# rslt_df.hist(bins = 1000)

In [59]:
df24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423986 entries, 0 to 423985
Data columns (total 97 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   CASE_NUMBER                     423986 non-null  object
 1   CASE_STATUS                     423986 non-null  object
 2   RECEIVED_DATE                   423986 non-null  datetime64[ns]
 3   DECISION_DATE                   423986 non-null  datetime64[ns]
 4   ORIGINAL_CERT_DATE              23130 non-null   datetime64[ns]
 5   VISA_CLASS                      423986 non-null  object
 6   JOB_TITLE                       423986 non-null  object
 7   SOC_CODE                        423986 non-null  object
 8   SOC_TITLE                       423986 non-null  object
 9   FULL_TIME_POSITION              423986 non-null  object
 10  BEGIN_DATE                      423986 non-null  datetime64[ns]
 11  END_DATE                        423986 non-null  datetime64[ns]
 12  TOTAL_WORKER_POSITIONS          423986 non-null  int64
 13  NEW_EMPLOYMENT                  423986 non-null  int64
 14  CONTINUED_EMPLOYMENT            423986 non-null  int64
 15  CHANGE_PREVIOUS_EMPLOYMENT      423986 non-null  int64
 16  NEW_CONCURRENT_EMPLOYMENT       423986 non-null  int64
 17  CHANGE_EMPLOYER                 423986 non-null  int64
 18  AMENDED_PETITION                423986 non-null  int64
 19  EMPLOYER_NAME                   423986 non-null  object
 20  TRADE_NAME_DBA                  37220 non-null   object
 21  EMPLOYER_ADDRESS1               423986 non-null  object
 22  EMPLOYER_ADDRESS2               193486 non-null  object
 23  EMPLOYER_CITY                   423986 non-null  object
 24  EMPLOYER_STATE                  423914 non-null  object
 25  EMPLOYER_POSTAL_CODE            423986 non-null  object
 26  EMPLOYER_COUNTRY                423986 non-null  object
 27  EMPLOYER_PROVINCE               23149 non-null   object
 28  EMPLOYER_PHONE                  423986 non-null  int64
 29  EMPLOYER_PHONE_EXT              24254 non-null   float64
 30  NAICS_CODE                      423986 non-null  int64
 31  EMPLOYER_POC_LAST_NAME          423986 non-null  object
 32  EMPLOYER_POC_FIRST_NAME         423983 non-null  object
 33  EMPLOYER_POC_MIDDLE_NAME        72853 non-null   object
 34  EMPLOYER_POC_JOB_TITLE          423986 non-null  object
 35  EMPLOYER_POC_ADDRESS1           423986 non-null  object
 36  EMPLOYER_POC_ADDRESS2           199625 non-null  object
 37  EMPLOYER_POC_CITY               423986 non-null  object
 38  EMPLOYER_POC_STATE              423683 non-null  object
 39  EMPLOYER_POC_POSTAL_CODE        423986 non-null  object
 40  EMPLOYER_POC_COUNTRY            423986 non-null  object
 41  EMPLOYER_POC_PROVINCE           3776 non-null    object
 42  EMPLOYER_POC_PHONE              423986 non-null  int64
 43  EMPLOYER_POC_PHONE_EXT          21684 non-null   float64
 44  EMPLOYER_POC_EMAIL              412515 non-null  object
 45  AGENT_REPRESENTING_EMPLOYER     423986 non-null  object
 46  AGENT_ATTORNEY_LAST_NAME        309934 non-null  object
 47  AGENT_ATTORNEY_FIRST_NAME       309933 non-null  object
 48  AGENT_ATTORNEY_MIDDLE_NAME      155872 non-null  object
 49  AGENT_ATTORNEY_ADDRESS1         309934 non-null  object
 50  AGENT_ATTORNEY_ADDRESS2         247623 non-null  object
 51  AGENT_ATTORNEY_CITY             309934 non-null  object
 52  AGENT_ATTORNEY_STATE            295136 non-null  object
 53  AGENT_ATTORNEY_POSTAL_CODE      309934 non-null  object
 54  AGENT_ATTORNEY_COUNTRY          309934 non-null  object
 55  AGENT_ATTORNEY_PROVINCE         35418 non-null   object
 56  AGENT_ATTORNEY_PHONE            309934 non-null  float64
 57  AGENT_ATTORNEY_PHONE_EXT        17330 non-null   float64
 58  AGENT_ATTORNEY_EMAIL_ADDRESS    309929 non-null  object
 59  LAWFIRM_NAME_BUSINESS_NAME      309934 non-null  object
 60  STATE_OF_HIGHEST_COURT          309126 non-null  object
 61  NAME_OF_HIGHEST_STATE_COURT     308858 non-null  object
 62  WORKSITE_WORKERS                423986 non-null  int64
 63  SECONDARY_ENTITY                423986 non-null  object
 64  SECONDARY_ENTITY_BUSINESS_NAME  91112 non-null   object
 65  WORKSITE_ADDRESS1               423986 non-null  object
 66  WORKSITE_ADDRESS2               129675 non-null  object
 67  WORKSITE_CITY                   423984 non-null  object
 68  WORKSITE_COUNTY                 423984 non-null  object
 69  WORKSITE_STATE                  423986 non-null  object
 70  WORKSITE_POSTAL_CODE            423986 non-null  object
 71  WAGE_RATE_OF_PAY_FROM           423986 non-null  float64
 72  WAGE_RATE_OF_PAY_TO             137825 non-null  float64
 73  WAGE_UNIT_OF_PAY                423986 non-null  object
 74  PREVAILING_WAGE                 423986 non-null  float64
 75  PW_UNIT_OF_PAY                  423986 non-null  object
 76  PW_TRACKING_NUMBER              719 non-null     object
 77  PW_WAGE_LEVEL                   391032 non-null  object
 78  PW_OES_YEAR                     393218 non-null  object
 79  PW_OTHER_SOURCE                 30049 non-null   object
 80  PW_OTHER_YEAR                   30049 non-null   float64
 81  PW_SURVEY_PUBLISHER             25254 non-null   object
 82  PW_SURVEY_NAME                  25253 non-null   object
 83  TOTAL_WORKSITE_LOCATIONS        423986 non-null  int64
 84  AGREE_TO_LC_STATEMENT           423986 non-null  object
 85  H_1B_DEPENDENT                  423986 non-null  object
 86  WILLFUL_VIOLATOR                423986 non-null  object
 87  SUPPORT_H1B                     112308 non-null  object
 88  STATUTORY_BASIS                 111658 non-null  object
 89  APPENDIX_A_ATTACHED             206 non-null     object
 90  PUBLIC_DISCLOSURE               423936 non-null  object
 91  PREPARER_LAST_NAME              215128 non-null  object
 92  PREPARER_FIRST_NAME             215130 non-null  object
 93  PREPARER_MIDDLE_INITIAL         60347 non-null   object
 94  PREPARER_BUSINESS_NAME          219715 non-null  object
 95  PREPARER_EMAIL                  218388 non-null  object
 96  WORKSITE_EMPLOYER               423986 non-null  object
dtypes: datetime64[ns](5), float64(8), int64(12), object(72)
memory usage: 313.8+ MB

In [60]:
df24['PW_WAGE_LEVEL'].unique()

array(['III', 'I', 'II', 'IV', nan], dtype=object)

In [61]:
min(df24['DECISION_DATE'])

Timestamp('2023-10-02 00:00:00')

In [62]:
max(df24['DECISION_DATE'])

Timestamp('2024-06-30 00:00:00')

In [63]:
len(df24)-len(df24.drop_duplicates())

0

In [64]:
len(df24['CASE_NUMBER'])-len(df24['CASE_NUMBER'].drop_duplicates())

0

In [65]:
# Export df to compressed .csv

compression_opts = dict(method='zip', archive_name='h1b_lca_fy24.csv')  

df24.to_csv('h1b_lca_fy24_data.zip', index=False, compression=compression_opts)

In [66]:
df24

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL,WORKSITE_EMPLOYER
0,I-200-24181-162896,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Quality Engineer,15-1253.00,Software Quality Assurance Analysts and Testers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
1,I-200-24181-162893,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Lead Software Engineer,15-1252.00,Software Developers,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
2,I-200-24181-162884,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Sr Software Engineer,15-1299.08,Computer Systems Engineers/Architects,Y,...,NaN,NaN,NaN,Disclose Business,McNeal,Antanina,NaN,Berry Appleman and Leiden LLP,alahatskaya@bal.com,Sabre GLBL Inc.
3,I-200-24181-162700,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Assistant Professor,25-1032.00,"Engineering Teachers, Postsecondary",Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"University of California, Berkeley"
4,I-200-24181-162574,Withdrawn,2024-06-29,2024-06-29,NaT,H-1B,Software Developer,15-1251.00,Computer Programmers,Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,"Cisco Systems, Inc."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423981,I-200-19297-106681,Certified - Withdrawn,2019-10-24,2023-11-01,2019-10-31,H-1B,Research Scientist I,17-2031.00,Biomedical Engineers,Y,...,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,Georgia Institute of Technology
423982,I-200-19296-103874,Certified - Withdrawn,2019-10-23,2024-03-04,2019-10-30,H-1B,Java Backend Microservices Designer / Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423983,I-200-19295-102430,Certified - Withdrawn,2019-10-22,2024-02-08,2019-10-29,H-1B,Senior Tibco Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,US BANK
423984,I-200-19288-087953,Certified - Withdrawn,2019-10-15,2024-03-04,2019-10-22,H-1B,BI Developer,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business and Employment,Potluri,Krishna,NaN,Stiaos Technologies,immi@stiaos.com,Stiaos Technologies
423985,I-200-19287-084931,Certified - Withdrawn,2019-10-14,2024-04-01,2019-10-21,H-1B,SENIOR SOFTWARE ENGINEER,15-1132.00,"Software Developers, Applications",Y,...,Yes,"Both $60,000 or higher in annual wage and Mast...",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN,JOHNSON CONTROLS INTERNATIONAL PLC